# fly.toml app configuration file generated for cookbook-proud-tree-5767 on 2024-08-21T23:23:32-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cookbook-proud-tree-5767'
primary_region = 'bos'
kill_signal = 'SIGTERM'

[build]

[env]
  PHX_HOST = 'cookbook-proud-tree-5767.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
